# Factor Graph
graph_params:
  useIsam: true # if false, then levenberg-marquardt is used
  smootherLag: 1.5                         #Lag of fixed lag smoother[seconds], not needed for ISAM2
  additionalOptimizationIterations: 0                  #Additional iterations of graph optimizer after update with new factors

# Outlier Rejection
outlier_params:
  gnssOutlierThreshold: 0.2 # in meters, if jumping more than this, it is considered as absent GNSS, occurs between two GNSS measurements

# Noise Parameters
noise_params:
  
  ### Preintegration
  integrationNoiseDensity: 1.0e-03         #continuous-time "Covariance" describing integration uncertainty, default: 1.0e-06
  biasAccOmegaPreInt: 1.0e-03                 #covariance of bias used for preintegration, default: 1.0e-2
  ## LiDAR
  poseBetweenNoise: [ 10.0, 10.0, 10.0, 2.0, 2.0, 2.0 ] # gnss [ 10.0, 10.0, 10.0, 2.0, 2.0, 2.0 ] # lidar: [ 1000.0, 1000.0, 1000.0, 100.0, 100.0, 100.0 ] #Noise of add between factor -ORDER RPY(rad) - XYZ(meters)
  poseUnaryNoise: [ 1000.0, 1000.0, 10.0, 10.0, 10.0, 10.0 ] # ORDER RPY(rad) - XYZ(meters) First tests:  [ 1000.0, 1000.0, 1000.0, 2.0, 2.0, 2.0 ]


# Relinearization
relinearization_params:
  positionReLinTh: 5.0e-10                    #Position linearization threshold
  rotationReLinTh: 1.0e-10                    #Rotation linearization threshold
  velocityReLinTh: 1.0e-10                     #Linear Velocity linearization threshold
  accBiasReLinTh: 1.0e-10                      #Accelerometer bias linearization threshold
  gyrBiasReLinTh: 1.0e-10                      #Gyroscope bias linearization threshold
  relinearizeSkip: 1
  enableRelinearization: true
  evaluateNonlinearError: false
  cacheLinearizedFactors: true
  enablePartialRelinearizationCheck: true
